AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  Exclude:
    - './*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'lib/tasks/**/*'
    - 'lib/generators/**/*'
    - 'features/**/*'
    - 'spec/**/*'
    - 'vendor/**/*'

####################################
## Customization for this project ##
####################################

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/MethodCalledOnDoEndBlock:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/PerceivedComplexity:
  Max: 9

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
