# Simplify running the application inside a container locally.
# Usage: `docker-compose up`
#
# Do not use docker-compose in production environments.
#
version: '3'

volumes:
  assets:

services:
  db:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  webapp:
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres@db/disclosure-checker
      - EXTERNAL_URL=http://localhost:8080
      - SECRET_KEY_BASE=c263472f8aa91f4a277002e9652f86f330e636358e2090d86ab4a4f0684cefe2
      - DATABASE_SSLMODE=disable
      - DISABLE_HTTPS=1
    depends_on:
      - db
    expose:
      - 3000
    volumes:
      - assets:/usr/src/app/public

  nginx:
    build:
      context: ./
      dockerfile: Dockerfile.nginx
    links:
      - webapp
    ports:
      - "8080:8081"
    volumes:
      - assets:/home/www/public
